name:                EarlyAnnPlugin
version:             0.1.0.0
github:              "m0ar/ghc-early-annotations-plugin"
license:             BSD3
author:              "Edvard Hübinette"
maintainer:          "edvard@hubinette.me"
copyright:           "2018 Edvard Hübinette"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Gets ANN pragma content efter parsing
# category:            Compiler extension

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/EarlyAnnPlugin#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  EarlyAnnPlugin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EarlyAnnPlugin

tests:
  EarlyAnnPlugin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EarlyAnnPlugin
